name: Java CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Tests
        run: mvn test

      - name: Start Server (Temporary Deploy)
        run: |
          nohup java -jar target/calculadora-api-*.jar &
          sleep 10  # Espera o servidor iniciar
          curl http://localhost:8080/api/calculadora/somar?a=5&b=3